categories:
  - key: club
    label: "Club"
    description: "Club nachten, disco feesten, after parties"
  - key: theater
    label: "Theater"
    description: "Stand up, voorstellingen"
  - key: concert
    label: "Concert"
    description: "Concerten van artiesten"
  - key: familie
    label: "Familie"
    description: "Familie events zoals culturele of religieuze bijeenkomsten"
